name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snake.svg


      - name: Commit and push changes
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add snake.svg
            git status  # Add this line for debugging
            git remote -v  # Add this line for debugging
            git commit -m "Update snake.svg"
            git push --set-upstream origin master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

